# Generated by Django 3.2.8 on 2021-10-09 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.contact'),
            preserve_default=False,
        ),
    ]
